# Generated by Django 4.2.17 on 2024-12-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="money",
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
        ),
    ]
