# Generated by Django 4.2.17 on 2024-12-21 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rename_user_id_user_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="username",
            new_name="user_id",
        ),
    ]
