# Generated by Django 4.2.17 on 2024-12-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_username_user_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="money",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
