# Generated by Django 4.2.17 on 2024-12-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_stock_alter_user_money_userstock"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="change_history",
            field=models.JSONField(default=list),
        ),
    ]
