# Generated by Django 4.2.17 on 2024-12-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_stock_change_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="current_price",
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name="user",
            name="money",
            field=models.IntegerField(default=1000000),
        ),
        migrations.AlterField(
            model_name="userstock",
            name="average_price",
            field=models.IntegerField(default=0),
        ),
    ]
