# Generated by Django 4.2.17 on 2024-12-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_stock_current_price_alter_user_money_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_value',
            field=models.JSONField(default=dict),
        ),
    ]
