# Generated by Django 4.2.17 on 2024-12-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_value그레이스_user_value뉴턴_user_value늘품_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='count_value',
        ),
    ]
